apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-chart-configmap-{{.Chart.Version}}
data:
  port: "8080"
  {{if eq .Values.env "staging"}}
  allowTesting: "true"
  {{else}}
  allowTesting: "false"
  {{end}}
